# Generated by Django 3.2b1 on 2021-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_comment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reciever',
            field=models.CharField(default='', max_length=255),
        ),
    ]
