# Generated by Django 3.2b1 on 2021-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_address_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_reciever',
            field=models.CharField(default="reciever's phone number", max_length=255),
        ),
    ]
