# Generated by Django 3.2b1 on 2021-06-17 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
