# Generated by Django 3.2b1 on 2021-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210617_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type_comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
