# Generated by Django 3.2b1 on 2021-06-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='content',
            field=models.CharField(default='cảm ơn bạn đã mua sản phẩm!', max_length=250),
        ),
    ]
